#!/bin/bash
set -ex

sleep 900 # Sleep for 15 minutes
# Sleep for a random number of seconds between 0 and 60
sleep $((RANDOM % 61))

# Log file
LOG_FILE="/var/log/nebius-updater-update.log"

# Start logging
echo "--- Auto apt upgrade started at $(date) ---" >> "$LOG_FILE"

# Update package lists
bash /usr/sbin/nebius-update-repo.sh >> "$LOG_FILE" 2>&1
if [ $? -ne 0 ]; then
    echo "Failed to update package lists" >> "$LOG_FILE"
    exit 1
fi

# Perform the upgrade
if ! DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --only-upgrade install nebius-observability-agent-updater >> "$LOG_FILE" 2>&1; then
    echo "Failed to perform upgrade" >> "$LOG_FILE"
    exit 1
fi

echo "--- Auto apt upgrade completed at $(date) ---" >> "$LOG_FILE"