#!/bin/sh
set -e

case "$1" in
    purge)
        ;;
    remove)
        systemctl disable nebius_observability_agent_updater.service
        if [ "$(systemctl is-system-running)" != "offline" ]; then # Check if running under systemd
            systemctl stop nebius_observability_agent_updater.service
        fi
        rm -rf /var/lib/nebius-observability-agent-updater
        ;;
    upgrade|failed-upgrade|disappear)
        ;;
    *)
        # Default case for unknown arguments
        ;;
esac

exit 0
