#!/bin/bash
set -ex
systemctl enable nebius_observability_agent_updater.service

systemctl restart nebius_observability_agent_updater.service

mkdir -p /var/lib/nebius-observability-agent-updater

chmod 0640 /etc/nebius-observability-agent-updater/config.yaml
